### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by sachinpatil3115** [INFO-526-S24/project-01-fight-club#1]
The following is the peer review of the project proposal by Energy Conservers. The team members that participated in this review are 

Sachin Patil -@sachinpatil3115

Cristian ortmann - @christian-ortmann

Abhishek Kumar - @Abhi291712

Tejas Bhawari - @tezz-us

Nick Ferrante - @n-ferrante

Monika Tejaswi - @KommareddyMonicaTejaswi

- Describe the goal of the project.

  The proposed project intends to find out the geographic distribution of UFO sightings, finding hotspots and any links 
  between the location and UFO form. Additionally, it intends to look at seasonal trends of the sighting and the impact of 
  astronomical events on reported sightings

- Describe the data used or collected.

  The TidyTuesday UFO sightings dataset compiles verified reports from various sources, containing details like location 
  (latitude and longitude), sighting time and date, UFO shape, and duration. It contains 3 datasets and gives details of 
  various variables like city, state, country_code, and shape,etc

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

  Overlaying the UFO sightings on a map to determine hotspots and see if there is any geographic correlation to the 
  hotspots. Then plot location of sightings with shape of the UFO to determine the correlation between location and shape 
  of UFO. They then breakdown the sightings by season and time of day to see if the diurnal cycle and season influence 
  sightings.

- Is there anything that is unclear from the proposal?

  One thing that could be a bit more clear is the inclusion of specific variables being used in the analysis plan. Although the 
  csv files being used are specified, it may be helpful to specify which variables from the data frames are going to be used to 
  create each plot.

- Provide constructive feedback on how the team might be able to improve their project.

  To enhance the project, the team could consider providing a more detailed overview of the statistical analyses they plan to 
  employ, offering insights into the methodologies. Incorporating a concise section on potential limitations and addressing 
  how these challenges will be managed would strengthen the project's robustness. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

  Team particularly interested in the analysis of seasonal patterns and the potential influence of astronomical events on UFO 
  sightings. Uncovering any trends or correlations related to specific months, seasons, or celestial occurrences could provide 
  intriguing insights. Highlighting these findings during the presentation would not only captivate the audience but also 
  contribute to a broader understanding of factors influencing UFO sightings. Additionally, exploring any significant 
  variations in reporting during certain astronomical events could add a fascinating dimension to the overall narrative.

- Provide constructive feedback on any issues with file and/or code organization.

  The analysis plan exhibits a well-organized approach, providing clear steps for investigating geographic distribution, 
  correlations between sighting locations and UFO shapes, and exploring seasonal and diurnal patterns. However, it would 
  be beneficial to elaborate on the specific plotting techniques or visualization tools planned for use, providing a more 
  detailed explanation of the libraries or packages employed.

- (Optional) Any further comments or feedback?

**Comment by AgastyaDeshraju** [comment]
Thank you for your feedback, we have taken into consideration all the points mentioned above. Good luck with your project!
