### ISSUE TITLE
Proposal peer review by Byte Coders

### ISSUE THREAD

**Issue by tanyageorge** [INFO-526-S24/project-01-fight-club#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Srinivasan Poonkundran - @kANNISTER
- Tanya Evita George - @tanyageorge
- Mobolaji Adewale - @Bolajiadewal3
- Rohit Vatsava Kalakala - @rohit-vatsava
- Noureen Mithaigar- @musketer26

**Describe the goal of the project.**

The goal of the project is to analyze the geographic distributions of UFOs, where they are possibly most prevalent to be sighted and any correlations between the areas of sightings, UFO shapes, seasonal patterns and astronomical events. Additionally, assessing whether specific shapes are more relevant in certain areas.

**Describe the data used or collected.**

- The data has been sourced from the National UFO Reporting Center.  
- The whole dataset consists of 3 dataframes- 'ufo_sightings', 'places', 'days_parts_map'.
- It consist of important information such as, the location, time and date of the sighting and the shape of the apparent UFO.

**Describe how the research question will be answered, e.g. what approaches / methods will be used.**

Description of question 1:

- The geographical locations and the hotspots where the sightings are most prevalent will be plotted on two different maps.
- A stacked bar chart will be plotted to show the relationship between the location and the shape of the UFOs

Description of question 2:

- UFO sightings are grouped based on the seasons of the year.
- Any patterns in these very sightings particular to a season will be visualized through a time-series analysis plot.
- Any correlations between UFO sightings and astronomical events will be plotted.

**Is there anything that is unclear from the proposal?**

- It is unclear what parameters are being used for each question neither have they been explained.
- It is not clear whether there are any data pre-processing procedures that is necessary and will be done.

**Provide constructive feedback on how the team might be able to improve their project.**
 
If its possible, try to make the questions a little distinct from each other.

**What aspect of this project are you most interested in and would like to see highlighted in the presentation.**

- We are very interested to find out which are the cities/areas that have reported the most UFO sightings and looking forward to see one.
- We are also eager to find out if astronomical events truly affect the possibility of a sighting.  

**Provide constructive feedback on any issues with file and/or code organization.**

- Code fold can be added.
- Printing the dataframe could have been more clearer.

**Any further comments or feedback?**

No references have been added- link of the actual dataset or source, author etc.

**Comment by AgastyaDeshraju** [comment]
Thank you for your feedback, we have taken into consideration all the points mentioned above. Good luck with your project!
