### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by christian-ortmann** [INFO-526-S24/project-01-fight-club#5]
The following is the peer review of the Presentation proposal by The Power of The Voters. The team members that participated in this review are 

Christian Ortmann @christian-ortmann 
Abishek Kumar @Abhi291712
Nick Ferrante @n-ferrante
Sachin Patil @sachinpatil3115
Tejas Bhawari @tezz-us
Kommareddy Monica Tejaswi @KommareddyMonicaTejaswi

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes, they separate the data into multiple facets such as a time when sightings occur and shape of the UFO. They were able to find multiple insights from each visualization.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, there are multiple visualizations that reflect different facets of the data such as timeliness of sightings and UFO shapes.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project? Yes, the plots flow nicely with the order and content of their insight. One thing I did not see was comments on the limitations of the data.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Yes, they had lots of interesting visuals as well in the background of the plots. I like how their graph for sightings in the US are interactive and can be zoomed in and out.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project? They did a great job of presenting, but it seems like some people knew more about what they were talking about than others. Not everyone said something meaningful.

**Comment by naitik2608** [comment]
Thank you for the valuable feedback!

Some plots required more explanation because they directly correlated with external factors. It might have given the impression that some people did more research but I can assure you that everyone put in equal effort into making this project.
