### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by n-ferrante** [INFO-526-S24/project-01-fight-club#6]
The following is the peer review of the Presentation proposal by Fight Club. The team members that participated in this review are 

- Christian Ortmann - @christian-ortmann
- Sachin Patil - @sachinpatil3115
- Abhishek Kumar - @Abhi291712
- Tejas Bhawari - @teza-us
- Monica Kommareddy - @KommareddyMoicaTejaswi
- Nick Ferrante - @n-ferrante 

- Content: Is the research question well designed and is the data being used relevant to the research question?

The research questions are well thought out, incorporating the interesting information that is related to UFO's such as astronomical events. The data being used is relevant to the research question as well.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Appropriate visualizations were used and interpreted correctly. I liked how they considered factors outside of the data set to answer the question of why a certain amount of sightings might occur more so in one area than another.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The project is carefully thought out, and it is apparent that time and effort went into creating it. I really liked the interactive map which allowed the group to zoom into the heat map that they had displayed prior, and I also liked how real world context was included specifically with the comment of the potential of Hollywood playing a role in increasing sightings.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides are well organized and simply fashioned for easy interpretation. The figures were clear and well explained, with easily interpretable labels and legends.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

The team did a good job of presenting with everyone providing a meaningful contribution. The team seemed well practiced and well prepared.

**Comment by naitik2608** [comment]
Thank you so much for the valuable feedback!
